image: golang:1.9.2-alpine

variables:
  REPO_NAME: github.com/batazor/go-auth

before_script:
  - mkdir -p $GOPATH/src/$REPO_NAME
  - ln -svf $CI_PROJECT_DIR/* $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME
  - apk add --no-cache git gcc
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure

stages:
    - test
    - build

format:
    stage: test
    script:
      - go fmt $(go list ./... | grep -v /vendor/)
      - go vet $(go list ./... | grep -v /vendor/)
      - go test -race $(go list ./... | grep -v /vendor/)
    only:
      - /^(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.?(?:0|[1-9]\d*)?$/
    except:
      - branches

compile:
    stage: build
    script:
      - docker build -t registry.gitlab.com/micro-company/go-auth .
      - docker push registry.gitlab.com/micro-company/go-auth
      - docker build -t registry.gitlab.com/micro-company/go-auth:$CI_COMMIT_TAG .
      - docker push registry.gitlab.com/micro-company/go-auth:$CI_COMMIT_TAG
    only:
      - /^(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.?(?:0|[1-9]\d*)?$/
    except:
      - branches

